### ISSUE TITLE
Search highlighting may break markup

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#366]
See https://cmsimpleforum.com/viewtopic.php?f=10&t=14178.

**Comment by cmb69** [comment]
This is more serious than I thought. Actually, any HTML entity on a page can be searched, breaking the markup. For instance, <https://www.cmsimple-xh.org/?privacy-protection&search=amp>.

**Comment by manu37** [comment]
I'm not sure wether this issue is done or not. Fixed with #366 or still pending with 2cb7e84?

**Comment by cmb69** [comment]
Nope, still not fixed. PoC: http://localhost/?Content&search=lt. Might make sense to switch to the JS search for XH 1.7.3.

**Comment by cmb69** [comment]
Frankly, I do not like the fix provided in PR #436 mainly for two reasons:

* it may highlight search words outside of the actual page content, i.e. words which would not have been found by the search
* we loose the (easy) ability to have tests for the search hightlighting

Therefore, I [ported the JS solution to PHP](https://github.com/cmsimple-xh/cmsimple-xh/pull/437); this is likely the best solution, but besides that PHP's DOM implementation has some issues, it feels a bit strange to actually work with the DOM only for this functionality, whereas elsewhere CMSimple_XH relies on string manipulation for such purposes. At least, I don't like the idea to introduce this in a revision release.

Thus, I had a closer look at the regular expression solution, and it seems that PR #437 is good enough for now.

Which solution would be preferred by others?

**Comment by manu37** [comment]
I don't find your PHP DOM implementation but I go for your #437

**Comment by cmb69** [comment]
Oops, here's the PHP DOM implementation: https://gist.github.com/cmb69/e711ed84a64b8e9816492e8535bb930b
